package checkpoint

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/nonsugar-go/tomato-ui/internal/utmconv/exporter/excel"
	"github.com/nonsugar-go/tomato-ui/internal/utmconv/model"
)

func ParseCheckPoint(app *model.App) {
	// app.Filename: show package filename (ex: show_package-2026-05-06_00-16-27.tar.gz)
	outFile := "checkpoint_param.xlsx" // output Excel file name

	e := excel.NewExcel(outFile)
	defer e.Close()
	err := processTarGzip(app.Filename, func(tempDir string) error {
		a := &AppEnv{E: e, InDir: tempDir}

		a.parseCPObjects()
		a.parseAccessRules()
		a.parseNATRules()

		return nil
	})
	if err != nil {
		slog.Error("failed to parse show package", slog.String("file", app.Filename))
		return
	}
	slog.Info("Excel file saved", slog.String("file", outFile))
}

type AppEnv struct {
	E     *excel.Excel
	InDir string
	Name  map[string]string
}

func (a *AppEnv) GetNamesByUIDs(uids []string) []string {
	names := make([]string, 0, len(uids))
	for _, uid := range uids {
		if name, ok := a.Name[uid]; ok {
			names = append(names, name)
		} else {
			slog.Warn("Failed to convert uid to name", slog.String("uid", uid))
		}
	}
	sort.Slice(names, func(i, j int) bool {
		a := strings.ToLower(names[i])
		b := strings.ToLower(names[j])
		if a == b {
			return names[i] < names[j]
		}
		return a < b
	})
	return names
}

func (a *AppEnv) JoinNames(uids []string) string {
	return join(a.GetNamesByUIDs(uids))
}

func (a *AppEnv) parseAccessRules() {
	pattern := filepath.Join(a.InDir, "* Network-Management server.json")
	files, err := filepath.Glob(pattern)
	if err != nil {
		slog.Error("fail to find files",
			slog.String("pattern", pattern), slog.String("error", err.Error()))
		os.Exit(1)
	}

	for _, file := range files {
		ruleName := strings.TrimSuffix(filepath.Base(file), " Network-Management server.json")
		var accessRules []AccessRule
		jsonData, err := os.ReadFile(file)
		if err != nil {
			slog.Error("Faild to read a file", slog.String("filename", file), slog.String("error", err.Error()))
			continue
		}
		err = json.Unmarshal(jsonData, &accessRules)
		if err != nil {
			slog.Error("JSON error", slog.String("error", err.Error()))
			continue
		}

		a.E.NewSheet("Access Rules - " + ruleName)
		a.E.Println("No", "Name", "Enabled", "Negate", "Sources", "Negate", "Destinations", "Negate", "Services", "Action",
			"Track", "Per Connection", "Per Session", "Enable Firewall Session", "Alert", "Accounting",
			"InstallOn", "Comments", "CustomField1", "CustomField2", "CustomField3")
		for _, r := range accessRules {
			if r.Type == "access-section" {
				a.E.Println("", fmt.Sprintf("%s - From %d to %d", r.Name, r.From, r.To))
			} else {
				a.E.Println(
					itoa(r.RuleNumber), r.Name, b2s(r.Enabled),
					b2s(r.SourceNegate), a.JoinNames(r.Source),
					b2s(r.DestinationNegate), a.JoinNames(r.Destination),
					b2s(r.ServiceNegate), a.JoinNames(r.Service),
					a.Name[r.Action],
					a.Name[r.Track.Type], b2s(r.Track.PerConnection), b2s(r.Track.PerSession), b2s(r.Track.EnableFirewallSession),
					r.Track.Alert, b2s(r.Track.Accounting),
					a.JoinNames(r.InstallOn),
					r.Comments,
					r.CustomFields.Field1,
					r.CustomFields.Field2,
					r.CustomFields.Field3,
				)
			}
		}
		a.E.AddTable()
	}
}

func (a *AppEnv) parseNATRules() {
	pattern := filepath.Join(a.InDir, "* NAT-Management server.json")
	files, err := filepath.Glob(pattern)
	if err != nil {
		slog.Error("fail to find files",
			slog.String("pattern", pattern), slog.String("error", err.Error()))
		os.Exit(1)
	}

	for _, file := range files {
		ruleName := strings.TrimSuffix(filepath.Base(file), " NAT-Management server.json")
		var NATRules []NATRule
		jsonData, err := os.ReadFile(file)
		if err != nil {
			slog.Error("Faild to read a file", slog.String("filename", file), slog.String("error", err.Error()))
			continue
		}
		err = json.Unmarshal(jsonData, &NATRules)
		if err != nil {
			slog.Error("JSON error", slog.String("error", err.Error()))
			continue
		}

		a.E.NewSheet("NAT Rules - " + ruleName)
		a.E.Println("No", "Name", "Enabled", "Method", "AutoGen", "OrigSources", "OrigDestinations", "OrigServices",
			"TransSources", "TransDestinations", "TransServices", "InstallOn", "Comments")
		for _, r := range NATRules {
			if r.Type == "nat-section" {
				a.E.Println("", fmt.Sprintf("%s - From %d to %d", r.Name, r.From, r.To))
			} else {
				a.E.Println(strconv.Itoa(r.RuleNumber), r.Name, b2s(r.Enabled),
					r.Method, b2s(r.AutoGenerated),
					a.Name[r.OriginalSource],
					a.Name[r.OriginalDestination],
					a.Name[r.OriginalService],
					a.Name[r.TranslatedSource],
					a.Name[r.TranslatedDestination],
					a.Name[r.TranslatedService],
					a.JoinNames(r.InstallOn),
					r.Comments,
				)
			}
		}
		a.E.AddTable()
	}
}

func (a *AppEnv) parseCPObjects() {
	pattern := filepath.Join(a.InDir, "*_objects.json")
	files, err := filepath.Glob(pattern)
	if err != nil {
		slog.Error("fail to find files",
			slog.String("pattern", pattern), slog.String("error", err.Error()))
		os.Exit(1)
	}

	var tmpCPObjs []CPObject
	for _, file := range files {
		slog.Info("processing", slog.String("file", file))

		data, err := os.ReadFile(file)
		if err != nil {
			slog.Error("fail to read file",
				slog.String("file", file), slog.String("error", err.Error()))
			continue
		}

		var objs []CPObject
		if err := json.Unmarshal(data, &objs); err != nil {
			slog.Error("fail to unmarshal JSON",
				slog.String("file", file), slog.String("error", err.Error()))
			continue
		}
		tmpCPObjs = append(tmpCPObjs, objs...)
	}

	exists := make(map[string]struct{}, len(tmpCPObjs))
	cpObjs := make([]CPObject, 0, len(tmpCPObjs))
	for _, obj := range tmpCPObjs {
		if _, ok := exists[obj.Uid]; ok {
			continue
		}
		exists[obj.Uid] = struct{}{}
		cpObjs = append(cpObjs, obj)
	}

	slog.Info("count of objects", slog.Int("count", len(cpObjs)))

	byType := make(map[string][]*CPObject)
	for i := range cpObjs {
		obj := &cpObjs[i]
		byType[obj.Type] = append(byType[obj.Type], obj)
	}
	for _, objs := range byType {
		sort.Slice(objs, func(i, j int) bool {
			a := strings.ToLower(objs[i].Name)
			b := strings.ToLower(objs[j].Name)
			if a == b {
				return objs[i].Name < objs[j].Name
			}
			return a < b
		})
	}

	keys := make([]string, 0, len(byType))
	for k := range byType {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		a := strings.ToLower(keys[i])
		b := strings.ToLower(keys[j])
		if a == b {
			return keys[i] < keys[j]
		}
		return a < b
	})

	for _, typeName := range keys {
		count := len(byType[typeName])
		slog.Info("objects of type", slog.String("type", typeName), slog.Int("count", count))
	}

	uidToName := make(map[string]string, len(cpObjs))
	for _, o := range cpObjs {
		uidToName[o.Uid] = o.Name
	}
	a.Name = uidToName

	a.writeCPObjectsExcel(byType)
}

func (a *AppEnv) writeCPObjectsExcel(byType map[string][]*CPObject) error {
	a.E.NewSheet("host")
	a.E.Println("Name", "IPv4 Addr", "IPv6 Addr", "Tags", "Comments")
	for _, o := range byType["host"] {
		a.E.Println(o.Name, o.IPv4Address, o.IPv6Address, joinNames(o.Tags), o.Comments)
	}
	a.E.AddTable()

	a.E.NewSheet("network")
	a.E.Println("Name", "Subnet4", "len4", "Subnet6", "len6", "Tags", "Comments")
	for _, o := range byType["network"] {
		a.E.Println(o.Name, o.Subnet4, strconv.Itoa(o.MaskLength4), o.Subnet6, strconv.Itoa(o.MaskLength6),
			joinNames(o.Tags), o.Comments)
	}
	a.E.AddTable()

	a.E.NewSheet("dns-domain")
	a.E.Println("Name", "Is-sub-domain", "Tags", "Comments")
	for _, o := range byType["dns-domain"] {
		a.E.Println(o.Name, b2s(o.IsSubDomain), joinNames(o.Tags), o.Comments)
	}
	a.E.AddTable()

	a.E.NewSheet("group")
	a.E.Println("Name", "members", "Tags", "Comments")
	for _, o := range byType["group"] {
		members := make([]string, 0, len(o.Members))
		for _, uid := range o.Members {
			members = append(members, a.Name[uid])
		}
		sort.Slice(members, func(i, j int) bool {
			a := strings.ToLower(members[i])
			b := strings.ToLower(members[j])
			if a == b {
				return members[i] < members[j]
			}
			return a < b
		})

		if len(members) == 0 {
			a.E.Println(o.Name, "", joinNames(o.Tags), o.Comments)
		} else {
			for i, m := range members {
				if i == 0 {
					a.E.Println(o.Name, m, joinNames(o.Tags), o.Comments)
				} else {
					a.E.Println("", m)
				}
			}
		}
	}
	a.E.AddTable()

	a.E.NewSheet("service-tcp")
	a.E.Println("Name", "port", "source-port", "Tags", "Comments")
	for _, o := range byType["service-tcp"] {
		a.E.Println(o.Name, o.Port, o.SourcePort, joinNames(o.Tags), o.Comments)
	}
	a.E.AddTable()

	a.E.NewSheet("service-udp")
	a.E.Println("Name", "port", "source-port", "Tags", "Comments")
	for _, o := range byType["service-udp"] {
		a.E.Println(o.Name, o.Port, o.SourcePort, joinNames(o.Tags), o.Comments)
	}
	a.E.AddTable()

	a.E.NewSheet("service-group")
	a.E.Println("Name", "members", "Tags", "Comments")
	for _, o := range byType["service-group"] {
		members := make([]string, 0, len(o.Members))
		for _, uid := range o.Members {
			members = append(members, a.Name[uid])
		}
		sort.Slice(members, func(i, j int) bool {
			a := strings.ToLower(members[i])
			b := strings.ToLower(members[j])
			if a == b {
				return members[i] < members[j]
			}
			return a < b
		})

		if len(members) == 0 {
			a.E.Println(o.Name, "", joinNames(o.Tags), o.Comments)
		} else {
			for i, m := range members {
				if i == 0 {
					a.E.Println(o.Name, m, joinNames(o.Tags), o.Comments)
				} else {
					a.E.Println("", m)
				}
			}
		}
	}
	a.E.AddTable()

	return nil
}
