package main

// Base Check Point Object
type BaseCPObject struct {
	Uid  string `json:"uid"`
	Name string `json:"name"`
	Type string `json:"type"`
}

// Check Point Object
type CPObject struct {
	BaseCPObject

	Comments string     `json:"comments,omitempty"`
	Tags     []CPObject `json:"tags,omitempty"`
	Color    string     `json:"color,omitempty"`

	// host
	IPv4Address string `json:"ipv4-address,omitempty"`
	IPv6Address string `json:"ipv6-address,omitempty"`

	// network
	Subnet4     string `json:"subnet4,omitempty"`
	MaskLength4 int    `json:"mask-length4,omitempty"`
	Subnet6     string `json:"subnet6,omitempty"`
	MaskLength6 int    `json:"mask-length6"`

	// dns-domain
	IsSubDomain bool `json:"is-sub-domain,omitempty"`

	// group / service-group
	Members []string `json:"members,omitempty"`

	// service-tcp / service-udp
	Port       string `json:"port,omitempty"`
	SourcePort string `json:"source-port,omitempty"`
}

type Track struct {
	Type                  string `json:"type,omitempty"` // uid
	PerConnection         bool   `json:"per-connection,omitempty"`
	PerSession            bool   `json:"per-session,omitempty"`
	EnableFirewallSession bool   `json:"enable-firewall-session,omitempty"`
	Alert                 string `json:"alert,omitempty"`
	Accounting            bool   `json:"accounting,omitempty"`
}

// Access Rule
type AccessRule struct {
	BaseCPObject

	// "access-section"
	From int `json:"from,omitempty"`
	To   int `json:"to,omitempty"`

	// "access-rule"
	Comments string     `json:"comments,omitempty"`
	Tags     []CPObject `json:"tags,omitempty"`

	RuleNumber        int      `json:"rule-number,omitempty"`
	Enabled           bool     `json:"enabled,omitempty"`
	SourceNegate      bool     `json:"source-negate,omitempty"`
	Source            []string `json:"source,omitempty"`
	DestinationNegate bool     `json:"destination-negate,omitempty"`
	Destination       []string `json:"destination,omitempty"`
	ServiceNegate     bool     `json:"service-negate,omitempty"`
	Service           []string `json:"service,omitempty"`
	ServiceResource   string   `json:"service-resource,omitempty"`
	ContentDirection  string   `json:"content-direction,omitempty"`
	ContentNegate     bool     `json:"content-negate,omitempty"`
	Content           []string `json:"content,omitempty"`

	Vpn    []string `json:"vpn,omitempty"`
	Action string   `json:"action,omitempty"`

	Track Track `json:"track"`

	InstallOn    []string `json:"install-on,omitempty"`
	CustomFields struct {
		Field1 string `json:"field-1,omitempty"`
		Field2 string `json:"field-2,omitempty"`
		Field3 string `json:"field-3,omitempty"`
	} `json:"custom-fields"`
}

// NAT Rule
type NATRule struct {
	BaseCPObject

	// nat-section
	From int `json:"from,omitempty"`
	To   int `json:"to,omitempty"`

	// nat-rule
	Comments string     `json:"comments,omitempty"`
	Tags     []CPObject `json:"tags,omitempty"`

	RuleNumber    int    `json:"rule-number,omitempty"`
	Enabled       bool   `json:"enabled,omitempty"`
	Method        string `json:"method,omitempty"`
	AutoGenerated bool   `json:"auto-generated,omitempty"`

	OriginalSource      string `json:"original-source,omitempty"`
	OriginalDestination string `json:"original-destination,omitempty"`
	OriginalService     string `json:"original-service,omitempty"`

	TranslatedSource      string `json:"translated-source,omitempty"`
	TranslatedDestination string `json:"translated-destination,omitempty"`
	TranslatedService     string `json:"translated-service,omitempty"`

	InstallOn []string `json:"install-on,omitempty"`
}
